### ISSUE TITLE
About Eq 9 in the paper

### ISSUE THREAD

**Issue by KFClpy** [cuiziteng/Aleth-NeRF#14]
Great work, but I have a question. Is the implementation of volume rendering in the code consistent with Eq. 9 in the paper? From my understanding, the implementation in the code directly multiplies the local occlusion field darkness from the network output with trans. I interpret this to mean that in the implementation of trans in the code, the trans of a point is only influenced by the occlusion field at the current position, without considering the occlusion field before this point. As I'm relatively new to NERF, my understanding of the paper may not be thorough enough. Could you please address this issue?
In your code：
`weights_dark = alpha * accum_prod_dark
        comp_rgb_dark = (weights_dark[..., None] * rgb * darkness).sum(dim=-2)
        acc_dark = weights_dark.sum(dim=-1)`
In the paper：
![BNO{(8V7T42~OI6CPTLFH8W](https://github.com/cuiziteng/Aleth-NeRF/assets/69008052/61476475-f830-4d66-8b7d-b85bcf7e7cf8)

**Comment by cuiziteng** [comment]
Hello, thanks for you interests. 

(1). Beyond Local Concealing Fields, Global Concealing Fields have been added here: 
as a set of learnable network parameters (fixed in scene).  The existence of Global Concealing Fields serves, to some extent, to reduce the learning difficulty of Local Concealing Fields. Simultaneously, it also aligns with maintaining a degree of consistency in low lighting within the same scene.

<img width="996" alt="image" src="https://github.com/cuiziteng/Aleth-NeRF/assets/55396225/a1e14f13-06ea-4da1-845b-ac8edc31a210">

<img width="800" alt="image" src="https://github.com/cuiziteng/Aleth-NeRF/assets/55396225/f65f2035-b654-4b01-a56c-6e98abbcb973">

(2). Analyzing the Volume Rendering formula of NeRF, you will find that each particle's role includes self-illumination and obstructing the illumination of subsequent particles. Through visualization, we find that the Concealing Field is generated in the air where there are no particles (particle density = 0). Therefore, the role of the Concealing Field is to enhance the obstruction ability of preceding particles to subsequent particles.

see Fig.3 in our paper:

<img width="482" alt="image" src="https://github.com/cuiziteng/Aleth-NeRF/assets/55396225/f1e373fa-cef3-49cb-87db-b67121d375de">

**Comment by KFClpy** [comment]
Thank you for your reply. Your explanation is very clear, but my main confusion lies in the local concealing field, which is the "darkness" part in the code. If implemented like in the code, I believe the expressed formula is:
![Screenshot_2024-04-12-10-28-12-334_com android browser-edit](https://github.com/cuiziteng/Aleth-NeRF/assets/69008052/3685fb62-ef3c-42f7-b9dc-e44faa321a27)

Perhaps I have misunderstood. Could you please explain further?

**Comment by cuiziteng** [comment]
The shape of Local concealing fields is (Batch, 128) rather than (Batch, 1), where the Batch means pixel number **i** in this equation and **j** means volume particle 128 in this equation, so the Local concealing fields is calculate in the volume rendering part to join in the accumulation, and the equation you provide didn't show that.

**Comment by KFClpy** [comment]
Thank you for your response. My question is, if we want to remain consistent with eq9 in the article, does darkness also need to be multiplied cumulatively, like fine_dark and coarse_dark?

**Comment by cuiziteng** [comment]
Sure, as they both multiplied in particle-wise.

**Comment by KFClpy** [comment]
Thank you for your patient responses. That's all my questions. Congratulations on your paper being accepted, and also, thank you for your contributions to low-level NeRF.
