### ISSUE TITLE
Question about geometry.

### ISSUE THREAD

**Issue by StarsTesla** [cuiziteng/Aleth-NeRF#3]
Hi,there,
I was wonder that if it coulde rebuild a normal radiance(light) form low light condition, dose the geometry also rebuild well?

**Comment by cuiziteng** [comment]
Sure, due to this is an end-to-end work that injection low-light enhancement in NeRF's volume rendering stage, so the 3D geometry could also well build, especially comparing with some pre-processing methods (like Image/Video Enhancement + NeRF). 

Please see a demo show in our website (comparison with enhancement methods): 

https://cuiziteng.github.io/Aleth_NeRF_web/

**Comment by cuiziteng** [comment]
Hello,  the code and paper have been updated, please refer to the new version.

**Comment by StarsTesla** [comment]
Thx for that！I will check it out later.
